# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: My Envio Indexer
networks:
- id: 369
  rpc_config:
    url: https://rpc.pulsechain.com
  start_block: 21200000
  contracts:
  - name: shio
    address:
    - 0x7aE73C498A308247BE73688c09c96B3fd06dDB84
    handler: src/EventHandlers.ts
    events:
    - event: LogEvent(uint64 soul, uint64 aura, string LogLine)
